### ISSUE TITLE
I am under the age of 18, so can I somehow use Openode?

### ISSUE THREAD

**Issue by LublubXT** [martinlevesque/openode-hello-world#1]
Hi, I am 14, so under the age of 18. Is there anyway that I can use this? I have been looking for something that I can host my websites, and webapps, for free. I came across this, and openode was exactly what I was looking for, but as I was looking through the Terms of Use, I saw that I had to be 18 or older. So is there anyway that I can use this? I didn't know how to contact openode, without having to have an account with it first, so I went to Github and made an "Issue", and wrote this. Thanks!

**Comment by martinlevesque** [comment]
Hey, you can create an account here https://www.openode.io/users/register

Cheers

**Comment by LublubXT** [comment]
So I can use it even if I am 14? Thanks!
